# Generated by Django 4.1 on 2025-04-08 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Workout",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "workouts",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("members", models.ManyToManyField(to="octofit_tracker_app.user")),
            ],
            options={
                "db_table": "teams",
            },
        ),
        migrations.CreateModel(
            name="Leaderboard",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="octofit_tracker_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "leaderboard",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("activity_type", models.CharField(max_length=100)),
                ("duration", models.DurationField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="octofit_tracker_app.user",
                    ),
                ),
            ],
            options={
                "db_table": "activities",
            },
        ),
    ]
